name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install yarn
      run: npm install yarn
    - name: Switch to plugin folder
      run: cd babel-plugin-deobfuscate
    - name: Install dependencies
      run: yarn install --dev
    - name: Jest Code Coverage Report
      uses: ziishaned/jest-reporter-action@0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
