name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./babel-plugin-deobfuscate
    steps:    
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn install --dev
      working-directory: ${{ env.working-directory}} 
    - name: Jest
      uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # this is just an example, this could be any command that will trigger jest
        test-command: "cd ${{ env.working-directory}} ; yarn jest --coverage --updateSnapshot"
#    - name: Run jest
#      run: yarn jest --coverage --updateSnapshot
#      working-directory: ${{ env.working-directory}} 
